sales_invoice=					[
					{
						"invoiceCounter": "1",
						"transactionType": "B2C",
						"personType": "VATR",
						"invoiceTypeDesc": "STD",
						"currency": "MUR",
						"invoiceIdentifier": "test4",
						"invoiceRefIdentifier": "",
						"previousNoteHash": "prevNote",
						"totalVatAmount": "30",
						"totalAmtWoVatCur": "310.01",
						"totalAmtWoVatMur": "10.1",
						"totalAmtPaid": "6400",
						"invoiceTotal": "6700",
						"discountTotalAmount": "300",
						"dateTimeInvoiceIssued": "20221012 10:40:30",
						"seller": {
							"name": "Testing LTD",
							"tan": "27495069",
							"brn": "C17144716",
							"businessAddr": "Triolet",
							"businessPhoneNo": "2076000",
							"ebsCounterNo": "1",
							"cashierId": "Tommy"
						},
						"buyer": {
							"name": "James",
							"tan": "12345678",
							"brn": "",
							"businessAddr": "",
							"buyerType": "NVTR",
							"nic": ""
						},
						"itemList": [
							{
								"taxCode": "TC01",
								"nature": "GOODS",
								"currency": "MUR",
								"itemNo": "1",
								"productCodeMra": "pdtCode",
								"productCodeOwn": "pdtOwn",
								"itemDesc": "2",
								"quantity": "3",
								"unitPrice": "20",
								"discount": "0",
								"discountedValue": "10.1",
								"amtWoVatCur": "600",
								"amtWoVatMur": "50",
								"vatAmt": "10",
								"totalPrice": "60"
							},
							{
								"taxCode": "TC01",
								"nature": "GOODS",
								"itemNo": "2",
								"productCodeMra": "pdtCode",
								"productCodeOwn": "pdtOwn",
								"itemDesc": "2",
								"quantity": "3",
								"unitPrice": "20",
								"discount": "0",
								"discountedValue": "10.1",
								"amtWoVatCur": "600",
								"amtWoVatMur": "50",
								"vatAmt": "10",
								"totalPrice": "60"
							},
							{
								"taxCode": "TC01",
								"nature": "GOODS",
								"itemNo": "3",
								"productCodeMra": "pdtCode",
								"productCodeOwn": "pdtOwn",
								"itemDesc": "2",
								"quantity": "3",
								"unitPrice": "20",
								"discount": "0",
								"discountedValue": "10.1",
								"amtWoVatCur": "600",
								"amtWoVatMur": "50",
								"vatAmt": "10",
								"totalPrice": "60"
							},
							{
								"taxCode": "TC03",
								"nature": "GOODS",
								"itemNo": "4",
								"productCodeMra": "pdtCode",
								"productCodeOwn": "pdtOwn",
								"itemDesc": "2",
								"quantity": "3",
								"unitPrice": "20",
								"discount": "0",
								"discountedValue": "10.1",
								"amtWoVatCur": "600",
								"amtWoVatMur": "50",
								"vatAmt": "0",
								"totalPrice": "60"
							},
							{
								"taxCode": "TC03",
								"nature": "GOODS",
								"itemNo": "5",
								"productCodeMra": "pdtCode",
								"productCodeOwn": "pdtOwn",
								"itemDesc": "2",
								"quantity": "3",
								"unitPrice": "20",
								"discount": "0",
								"discountedValue": "10.1",
								"amtWoVatCur": "600",
								"amtWoVatMur": "50",
								"vatAmt": "0",
								"totalPrice": "60"
							},
							{
								"taxCode": "TC03",
								"nature": "GOODS",
								"itemNo": "61",
								"productCodeMra": "pdtCode",
								"productCodeOwn": "pdtOwn",
								"itemDesc": "2",
								"quantity": "3",
								"unitPrice": "20",
								"discount": "0",
								"discountedValue": "10.1",
								"amtWoVatCur": "600",
								"amtWoVatMur": "50",
								"vatAmt": "0",
								"totalPrice": "60"
							}
						],
						"salesTransactions": "CASH"
					}
				]
											